import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    tailwind: "src/tailwind.ts",
    "tailwind-preset": "src/tailwind-preset.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  sourcemap: true,
  onSuccess: async () => {
    const fs = await import("fs");
    const path = await import("path");
    const { pathToFileURL } = await import("url");

    const dist = path.join(process.cwd(), "dist");

    // Copy CSS to dist
    fs.copyFileSync(
      path.join(process.cwd(), "src", "tokens.css"),
      path.join(dist, "tokens.css"),
    );

    // Generate the Tailwind v4 `@theme` layer from `tailwindColors`.
    //
    // A CSS custom property alone mints NO utility in v4 — it has to be mapped
    // under `@theme` first. That mapping is 50-odd mechanical lines, and a
    // hand-written copy is exactly where a half-adopted layer comes from: map
    // four of the seven attention levels and `bg-testing-bg` silently produces
    // nothing at all. So it is DERIVED from the same `tailwindColors` object
    // the v3 preset consumes, which makes v3/v4 utility-name parity structural
    // rather than a thing to remember. `inline` keeps each utility pointing at
    // `var(--qontinui-*)`, so `.dark` still re-themes at runtime.
    const { tailwindColors } = await import(
      pathToFileURL(path.join(dist, "tailwind.js")).href
    );

    // One blank-line-separated section per group; a run of flat entries (the
    // semantic colors) shares a section.
    const sections: string[][] = [];
    let flat: string[] | null = null;
    for (const [group, value] of Object.entries(tailwindColors)) {
      if (typeof value === "string") {
        if (!flat) sections.push((flat = []));
        flat.push(`  --color-${group}: ${value};`);
        continue;
      }
      flat = null;
      sections.push(
        Object.entries(value as Record<string, string>).map(
          ([name, v]) => `  --color-${group}-${name}: ${v};`,
        ),
      );
    }

    const header = [
      "/**",
      " * Qontinui Design Tokens - Tailwind v4 theme layer",
      " *",
      " * GENERATED by tsup.config.ts from `tailwindColors` (src/tailwind.ts) —",
      " * do not edit. The utility names here are the same ones the v3 preset mints.",
      " *",
      ' * Usage (Tailwind v4), AFTER `@import "tailwindcss"`:',
      " *   @import '@qontinui/design-tokens/theme';",
      " *",
      " * It pulls in tokens.css itself, so it is the only import a v4 app needs.",
      " */",
      '@import "./tokens.css";',
      "",
      "@theme inline {",
    ].join("\n");

    const body = sections.map((lines) => lines.join("\n")).join("\n\n");
    fs.writeFileSync(path.join(dist, "theme.css"), header + "\n" + body + "\n}\n");
  },
});
